# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tokenize import String
import pymysql
from database import *


class Ui_edit(object):
    def setupUi(self, edit):
        edit.setObjectName("edit")
        edit.resize(454, 368)
        font = QtGui.QFont()
        font.setFamily("RSU")
        edit.setFont(font)
        self.label = QtWidgets.QLabel(edit)
        self.label.setGeometry(QtCore.QRect(150, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.editButton = QtWidgets.QPushButton(edit)
        self.editButton.setGeometry(QtCore.QRect(150, 270, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.editButton.setFont(font)
        self.editButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editButton.setCheckable(True)
        self.editButton.setObjectName("editButton")
        self.label_2 = QtWidgets.QLabel(edit)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(edit)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(edit)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(edit)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cancleButton = QtWidgets.QPushButton(edit)
        self.cancleButton.setGeometry(QtCore.QRect(260, 270, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cancleButton.setFont(font)
        self.cancleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancleButton.setCheckable(True)
        self.cancleButton.setObjectName("cancleButton")
        self.FecthButton = QtWidgets.QPushButton(edit)
        self.FecthButton.setGeometry(QtCore.QRect(370, 60, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FecthButton.setFont(font)
        self.FecthButton.setObjectName("FecthButton")
        self.deletedataButton = QtWidgets.QPushButton(edit)
        self.deletedataButton.setGeometry(QtCore.QRect(150, 320, 201, 41))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(20)
        self.deletedataButton.setFont(font)
        self.deletedataButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deletedataButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.deletedataButton.setAutoFillBackground(False)
        self.deletedataButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;\n"
"border: 1px solid #D5D8DC;")
        self.deletedataButton.setObjectName("deletedataButton")
        self.idcoffeetext = QtWidgets.QLineEdit(edit)
        self.idcoffeetext.setGeometry(QtCore.QRect(140, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idcoffeetext.setFont(font)
        self.idcoffeetext.setObjectName("idcoffeetext")
        self.menucoffeetext = QtWidgets.QLineEdit(edit)
        self.menucoffeetext.setGeometry(QtCore.QRect(140, 110, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menucoffeetext.setFont(font)
        self.menucoffeetext.setObjectName("menucoffeetext")
        self.descriptiontext = QtWidgets.QLineEdit(edit)
        self.descriptiontext.setGeometry(QtCore.QRect(140, 160, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.descriptiontext.setFont(font)
        self.descriptiontext.setObjectName("descriptiontext")
        self.pricetext = QtWidgets.QLineEdit(edit)
        self.pricetext.setGeometry(QtCore.QRect(140, 220, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pricetext.setFont(font)
        self.pricetext.setObjectName("pricetext")

        self.retranslateUi(edit)
        QtCore.QMetaObject.connectSlotsByName(edit)

    def retranslateUi(self, edit):
        _translate = QtCore.QCoreApplication.translate
        edit.setWindowTitle(_translate("edit", "Form"))
        self.label.setText(_translate("edit", "แก้ไขหรือลบเมนูกาแฟ"))
        self.editButton.setText(_translate("edit", "แก้ไข"))
        self.label_2.setText(_translate("edit", "ID"))
        self.label_3.setText(_translate("edit", "ชื่อเมนู"))
        self.label_4.setText(_translate("edit", "รายละเอียด"))
        self.label_5.setText(_translate("edit", "ราคา"))
        self.cancleButton.setText(_translate("edit", "ยกเลิก"))
        self.FecthButton.setText(_translate("edit", "ค้นหา"))
        self.deletedataButton.setText(_translate("edit", "ลบข้อมูลทั้งหมด"))
        self.FecthButton.clicked.connect(self.fecthID)
        self.editButton.clicked.connect(self.editDatabase)
        self.deletedataButton.clicked.connect(self.removeDatabase)
        self.cancleButton.clicked.connect(self.removeText)


    def fecthID(self):
        global COFFEE_ID
        COFFEE_ID = self.idcoffeetext.text()
        if COFFEE_ID == "":
            print("กรุณาใส่ไอดี")
        else:
            self.checkID()
    
    def checkID(self):
        global COFFEE_ID
        con = pymysql.connect(host="localhost", database="project python",
                              user=userSQL, password=passSQL, charset="utf8")
        cursor = con.cursor()
        cursor.execute(
            "SELECT MENU_NAME FROM coffee WHERE COFFEE_ID = %s", COFFEE_ID)
        MENU_NAME = cursor.fetchone()
        if MENU_NAME == None:
            self.idcoffeetext.setText("ไม่พบชื่อเมนู")
            self.menucoffeetext.setText("ไม่พบชื่อเมนู")
            self.descriptiontext.setText("ไม่พบชื่อเมนู")
            self.pricetext.setText("ไม่พบชื่อเมนู")
            print("ไม่พบไอดีเมนู")
        else:
            self.fetchDatabase()
    
    def fetchDatabase(self):  
        print('fetching database')
        con = pymysql.connect(host="localhost", database="project python",
                              user=userSQL, password=passSQL, charset="utf8")
        cursor = con.cursor()
        cursor.execute("SELECT MENU_NAME FROM coffee WHERE COFFEE_ID = %s", COFFEE_ID)
        MENU_NAME = cursor.fetchone()
        cursor.execute("SELECT MENU_DETAIL FROM coffee WHERE COFFEE_ID = %s", COFFEE_ID)
        MENU_DETAIL = cursor.fetchone()
        cursor.execute("SELECT MENU_PRICE FROM coffee WHERE COFFEE_ID = %s", COFFEE_ID)
        MENU_PRICE = cursor.fetchone()
        self.menucoffeetext.setText(MENU_NAME[0])
        self.descriptiontext.setText(MENU_DETAIL[0])
        self.pricetext.setText(str(MENU_PRICE[0]))
        con.close()
    
    def editDatabase(self): 
         ID = self.idcoffeetext.text()
         menu = self.menucoffeetext.text()
         description = self.descriptiontext.text()
         price = self.pricetext.text()
         if (ID == '' or menu == '' or description == '' or price == ''):
            print("Please fill all data")
         else:
            con = pymysql.connect(host="localhost", database="project python",
                                  user=userSQL, password=passSQL, charset="utf8")
            cursor = con.cursor()
            cursor.execute("UPDATE coffee SET MENU_NAME=%s, MENU_DETAIL=%s, MENU_PRICE=%s WHERE COFFEE_ID=%s",
                           ( menu, description, price,ID))
            print("Edit data successfully")
            con.commit()
    
    def removeDatabase(self):  
        ID = self.idcoffeetext.text()
        menu = self.menucoffeetext.text()
        description = self.descriptiontext.text()
        price = self.pricetext.text()
        if (COFFEE_ID == ''):
            print("Please fill Menu ID")
            self.messageBoxFillId('ผิดพลาด', 'กรุณาใส่ไอดีเมนู')
        else:
            con = pymysql.connect(host="localhost", database="project python",
                                  user=userSQL, password=passSQL, charset="utf8")
            cursor = con.cursor()
            checkBook = cursor.execute("SELECT COFFEE_ID FROM coffee WHERE COFFEE_ID = %s", COFFEE_ID)
            if checkBook == 0:
                print("ไม่พบเมนู")
            else:
                cursor.execute("DELETE FROM coffee WHERE COFFEE_ID = %s", COFFEE_ID)
                con.commit()
                print("ลบข้อมูลสำเร็จ")
                self.removeText()
                con.close()
    
    def removeText(self):  
        self.idcoffeetext.clear()
        self.menucoffeetext.clear()
        self.descriptiontext.clear()
        self.pricetext.clear()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit = QtWidgets.QWidget()
    ui = Ui_edit()
    ui.setupUi(edit)
    edit.show()
    sys.exit(app.exec_())

    # project python
    # MENU_NAME, MENU_DETAIL, MENU_PRICE
    # idcoffeetext.setText("")
    # menucoffeetext.setText("")
    # descriptiontext.setText("")
    # pricetext.setText("")
