# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import main


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 511)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(97, 64, 0);")
        self.usernameText = QtWidgets.QLineEdit(Dialog)
        self.usernameText.setGeometry(QtCore.QRect(140, 180, 240, 40))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.usernameText.setFont(font)
        self.usernameText.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    backgroud-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"backgroud-color: rgb(43, 45, 56);\n"
"}")
        self.usernameText.setObjectName("usernameText")
        self.passwordText = QtWidgets.QLineEdit(Dialog)
        self.passwordText.setGeometry(QtCore.QRect(140, 260, 240, 40))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.passwordText.setFont(font)
        self.passwordText.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    backgroud-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"backgroud-color: rgb(43, 45, 56);\n"
"}")
        self.passwordText.setObjectName("passwordText")
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(190, 340, 141, 51))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loginbutton.setFont(font)
        self.loginbutton.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(37,39,48);\n"
"    border-radius: 20px;\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    backgroud-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(48, 50, 62);\n"
"}\n"
"QPushButton:hover:pressed\n"
"{\n"
"  border: 2px solid rgb(255, 73, 73);\n"
"}")
        self.loginbutton.setObjectName("loginbutton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 80, 261, 51))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    Color: #FFF\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        Dialog.setWindowIcon(QtGui.QIcon(':image/icon.png'))
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.usernameText.setPlaceholderText(_translate("Dialog", "Username"))
        self.passwordText.setPlaceholderText(_translate("Dialog", "Password"))
        self.loginbutton.setText(_translate("Dialog", "Login"))
        self.label.setText(_translate("Dialog", "เข้าสู่ระบบ"))
        self.loginbutton.clicked.connect(self.callDatabase)

    def callDatabase(self):
        
        username = self.usernameText.text()
        passsword = self.passwordText.text()
        try:
          sqlConnection = pymysql.connect(host="localhost", database="project python", user=username, password=passsword,
                                        charset="utf8")
        
        except pymysql.err.OperationalError as e:
                print("Error %d: %s" % (e.args[0], e.args[1]))
                if(e.args[0]==1045):
                    print("Invalid username or password")
                elif(e.args[0]==1049):
                    print("Database not found")
                elif(e.args[0]==2003):
                    print("Server not found")
                elif(e.args[0]==2005):
                    print("Unknown host")
                elif(e.args[0]==2006):
                    print("Server has gone away")
                elif(e.args[0]==2013):
                    print("Lost connection to MySQL server during query")
                elif(e.args[0]==2019):
                    print("Access denied for user")
                elif(e.args[0]==2026):
                    print("Too many connections")
        else:
            print("Connection successful")
            self.openHomepage()
            sqlConnection.close()

    def openHomepage(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = main.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        closeWindows()

def closeWindows():
    Dialog.close()

def openHomepage2():
    Dialog2 = QtWidgets.QDialog()
    ui = main.Ui_uiHomePage()
    ui.setupUi(Dialog2)
    Dialog2.show()
    Dialog2.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
