# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from database import *


class Ui_signup(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.setFixedSize(425, 464)
        signup.setWindowIcon(QtGui.QIcon(':image/icon.png'))
        signup.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.lineEdit = QtWidgets.QLineEdit(signup)
        self.lineEdit.setGeometry(QtCore.QRect(170, 100, 221, 41))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(signup)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 160, 221, 41))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(signup)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 220, 221, 41))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(signup)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 280, 221, 41))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(signup)
        self.pushButton.setGeometry(QtCore.QRect(140, 350, 141, 61))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(signup)
        self.label.setGeometry(QtCore.QRect(80, 20, 291, 61))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(signup)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 111, 31))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(signup)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(signup)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(signup)
        self.label_5.setGeometry(QtCore.QRect(30, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("RSU")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "Admin Sign-up"))
        self.lineEdit.setPlaceholderText(_translate("signup", "FULL NAME"))
        self.lineEdit_2.setPlaceholderText(_translate("signup", "USERNAME"))
        self.lineEdit_3.setPlaceholderText(_translate("signup", "EMAIL"))
        self.lineEdit_4.setPlaceholderText(_translate("signup", "PASSWORD"))
        self.pushButton.setText(_translate("signup", "CONFIRM"))
        self.label.setText(_translate("signup", "ADMIN SIGN UP"))
        self.label_2.setText(_translate("signup", "FULL NAME"))
        self.label_3.setText(_translate("signup", "USERNAME"))
        self.label_4.setText(_translate("signup", "EMAIL"))
        self.label_5.setText(_translate("signup", "PASSWORD"))
        self.pushButton.clicked.connect(lambda: self.register())

    def register(self):
        fullname = self.lineEdit.text()
        username = self.lineEdit_2.text()
        email = self.lineEdit_3.text()
        password = self.lineEdit_4.text()
        con = pymysql.connect(host="localhost", database="project python",
                        user=userSQL, password=passSQL, charset="utf8")
        cursor = con.cursor()
        cursor.execute("select * from log_db where Fullname='"+ fullname +"' and Username='"+ username +"' and Email='"+ email +"' and Password='"+ password +"'")
        result = cursor.fetchone()
        
        if result:
            print('Already Exist')
        else:
            cursor.execute("insert into log_db values('"+ fullname +"', '"+ username +"', '"+ email +"', '"+ password +"')")
            con.commit()
            print('completed')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup = QtWidgets.QWidget()
    ui = Ui_signup()
    ui.setupUi(signup)
    signup.show()
    sys.exit(app.exec_())
